language: go

sudo: required
dist: trusty
services: docker

go:
  - '1.10'
go_import_path: github.com/praekeltfoundation/vault-gatekeeper-mesos

before_script:
  - docker run -d -p 8200:8200 --hostname vault --name vault vault server -dev -dev-root-token-id=vault-gatekeeper-test-token-id
script:
  - bash integration.sh
  - go vet .

after_script:
  - docker stop vault
  - docker rm vault
