language: go

sudo: required
dist: trusty
services: docker

go:
  - '1.10.x'

before_install:
  - make bootstrap
install:
  - dep ensure

before_script:
  - docker run -d -p 8200:8200 --hostname vault --name vault vault server -dev -dev-root-token-id=vault-gatekeeper-test-token-id
script:
  - bash integration.sh
  - '[[ -z "$(make fmt)" ]] || true'  # FIXME
  - make vet

after_script:
  - docker stop vault
  - docker rm vault

after_success:
  - bash <(curl -s https://codecov.io/bash)
